[package]
name = "secret_santa"
version = "0.1.0"
authors = ["Marien Leblanc <marien.leblanc@amersports.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
